name: Azure Github Sync

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./AzureGithubSync.ps1 -GithubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -AzureDevOpsPAT ${{ secrets.AZUREDEVOPSPAT }}
 